### ISSUE TITLE
Reject PATHs that contain ':'

### ISSUE THREAD

**Issue by hasufell** [treblacy/ep#1]
> Since \<colon\> is a separator in this context, directory names that might be used in PATH should not include a \<colon\> character.

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

**Comment by treblacy** [comment]
OK finally fixed after years :) of hiatus. 61173069ca9ffc71b8079bf31f54d7eaef5ec3b8
